name: publish CI

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: 'Release Type'
        options:
          - stg
          - patch
      release_branch_name:
        type: string
        required: true
        description: "Branch name (Without 'v' Ex: 1.0.0)"

env: 
  RELEASE_TYPE: ${{ inputs.release_type}}
  BRANCH_NAME: ${{ inputs.release_branch_name}}

jobs:
  create_tag:
    environment: Release
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Setup node 📥
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        registry-url: 'https://registry.npmjs.org'

    - name: Print Branch Name
      run: |
        echo "Branch Name: ${BRANCH_NAME}"

    - name: Setup Github Config
      run: | 
        git config user.name "Github Actions Bot KLTR"
        git config user.email "<>"

    - name: Create Branch 
      env:
        B_NAME: ${RELEASE_TYPE}/v${BRANCH_NAME}
      run: |
        echo "Branch Name: ${B_NAME}"
        git branch ${B_NAME} develop
        git push origin ${B_NAME}

    - name: Create Tag 🏷️
      env: 
        T_NAME: v${BRANCH_NAME}
      run: |
        git tag ${T_NAME} ${GITHUB_SHA}
        git push origin ${T_NAME}

    - name: Install package Manager 📥
      run: yarn install

    - name: Publish to NPM 📦
      run: yarn publish
      env: 
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_KLTR_AUTOMATION_PLAYER_TEAM }}
