name: tag CI

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: 'Release Type'
        options:
          - stg
          - patch
      release_tag_version:
        type: string
        required: true
        description: "Tag Version (Without 'v' Ex: 1.0.0)"
  
jobs:
  create_tag:
    environment: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Print Tag version
      run: |
        echo "Tag Version: $TAG"
      env: 
        TAG: ${{ inputs.release_tag_version }}
    - name: Setup Github Config
      run: | 
        git config user.name "Github Actions Bot KLTR"
        git config user.email "<>"
    - name: Create tag
      run: |
        git tag v${{ inputs.release_tag_version }} ${{ inputs.release_type }}/v${{ inputs.release_tag_version }}
        git push origin v${{ inputs.release_tag_version }}

